package com.codeline.demo.helper;

public class Constants {
    public final static String SUCCESS = "Success";
    public final static String BAD_REQUEST = "BAD REQUEST";
    public final static String COURSE_CREATE_REQUEST_NAME_NOT_VALID="NAME NOT VALID";
    public final static String COURSE_CREATE_REQUEST_INSTRUCTOR_ID_NOT_VALID="INSTRUCTOR NOT VALID";
    public final static String COURSE_CREATE_REQUEST_MARK_ID_NOT_VALID="MARKS NOT VALID";
    public final static String INSTRUCTOR_CREATE_REQUEST_NAME_NOT_VALID="NAME NOT VALID";
    public final static String INSTRUCTOR_CREATE_REQUEST_DEPARTMENT_ID_NOT_VALID="DEPARTMENT NOT VALID";
    public final static String DEPARTMENT_CREATE_REQUEST_NAME_NOT_VALID="NAME NOT VALID";
    public final static String MARKS_CREATE_REQUEST_STUDENT_NAME_NOT_VALID="STUDENT NAME NOT VALID";
    public final static String MARKS_CREATE_REQUEST_SCORE_NOT_VALID="SCORE NOT VALID";
    public final static Integer SCORE_UPPER_LIMIT=100;
    public final static Integer SCORE_LOWER_LIMIT=0;
    public final static String STUDENT_CREATE_REQUEST_FIRST_NAME_NOT_VALID="FIRST NAME NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_LAST_NAME_NOT_VALID="LAST NAME NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_EMAIL_NOT_VALID="EMAIL NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_DATE_OF_BIRTH_NOT_VALID="DATE 0F BIRTH NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_GENDER_NOT_VALID="GENDER NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_PHONE_NUMBER_NOT_VALID="PHONE NUMBER NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_ADDRESS_NOT_VALID="ADDRESS NOT VALID";
    public final static String PHONE_NUMBER_CREATE_REQUEST_NUMBER_NOT_VALID="NUMBER NOT VALID";
    public final static String PHONE_NUMBER_CREATE_REQUEST_COUNTRY_CODE_NOT_VALID="COUNTRY CODE NOT VALID";
    public final static String PHONE_NUMBER_CREATE_REQUEST_IS_LAND_LINE_NOT_VALID="LAND LINE NOT VALID";
    public final static String PHONE_NUMBER_CREATE_REQUEST_STUDENT_ID_NOT_VALID="STUDENT NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_HOUSE_NUMBER_NOT_VALID="HOUSE NUMBER NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_STREET_NOT_VALID="STREET NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_CITY_NOT_VALID="CITY NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_STATE_OR_PROVINCE_NOT_VALID="STATE OR PROVINCE NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_COUNTRY_NOT_VALID="COUNTRY NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_POSTAL_CODE_NOT_VALID="POSTAL CODE NOT VALID";












}
